### ISSUE TITLE
[Question]: Release, version tag and go.mod

### ISSUE THREAD

**Issue by Hellseher** [kballard/go-shellquote#13]
Hi!

I came here while refreshing dependencies for Guix package of
https://github.com/chmouel/clipman. Is there any plan to release the project or
add a version tag? It would improve the distribution experience. Also having
go.mod is a quite common for nowadays Golang projects.

Thanks,
Oleg

**Comment by lilyball** [comment]
This project hasn't been active in a long time and long predates the existence of `go.mod`. Barring any critical bugfixes, it's going to stay in its current state indefinitely, as I have not worked with Go for a very long time.

**Comment by Hellseher** [comment]
For anyone who needs above points covered I've made a fork which includes
go.mod, passed all lint checks and has a version tag
<https://github.com/Hellseher/go-shellquote>.
