### ISSUE TITLE
`\` should not be considered an escape character on Windows

### ISSUE THREAD

**Issue by AudriusButkevicius** [kballard/go-shellquote#8]
```
package main

import(
	"fmt"
	"github.com/kballard/go-shellquote"
)

func main(){
	x := `c:\foo.exe -user=x -pass=bar "something with spaces"`
	a, b := shellquote.Split(x)
	for i, v := range a {
		fmt.Println(i, v)
	}
	fmt.Println(b)
}
```

produces:

```
0 c:foo.exe
1 -user=x
2 -pass=bar
3 something with spaces
<nil>
```

**Comment by kballard** [comment]
Shellquote implements sh's word-splitting rules. It looks to me like you're trying to use it to split a command-line that is meant for something other than sh.

**Comment by AudriusButkevicius** [comment]
Well, splitting command line is a generic problem across various shells, not only applicable to sh.
I guess this package refers explicitly to splitting according to sh's rules, hence this is not a valid issue, and hence we need to work around it ourselves.

**Comment by kballard** [comment]
Yeah, sorry. I don't know anything about Windows's command-line splitting rules. And I'm also not an active Go developer anymore, so I'm not particularly inclined to expand the scope of this package.

Good luck solving your problem!
